# Generated by Django 5.1.2 on 2025-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Enter UserName')),
                ('password', models.CharField(max_length=20, verbose_name='Enter Password')),
                ('intro_firstname', models.CharField(max_length=10, verbose_name='Enter FirstName')),
                ('intro_middlename', models.CharField(max_length=10, verbose_name='Enter MiddleName')),
                ('intro_lastname', models.CharField(max_length=10, verbose_name='Enter LastName')),
                ('intro_image', models.FileField(default=None, null=True, upload_to='', verbose_name='Enter User Image')),
                ('intro_designation', models.CharField(max_length=10, verbose_name='Enter  Designation')),
                ('intro_address', models.TextField(verbose_name='Enter User Address')),
                ('intro_email', models.EmailField(max_length=254, verbose_name='Enter User Email')),
                ('intro_phone', models.CharField(max_length=13, verbose_name='Enter User Mobile Number')),
                ('intro_summary', models.CharField(max_length=50, verbose_name='Enter User Summary')),
                ('achi_title', models.CharField(max_length=20, verbose_name='Enter  Achievement Title')),
                ('achi_description', models.TextField(verbose_name='Enter  Achievement Description')),
                ('exp_title', models.CharField(max_length=20, verbose_name='Enter  Experience Title')),
                ('exp_company', models.CharField(max_length=20, verbose_name='Enter  Experience Company')),
                ('exp_location', models.CharField(max_length=20, verbose_name='Enter  Experience Location')),
                ('exp_start_date', models.DateField(verbose_name='Enter  Experience Start Date')),
                ('exp_end_date', models.DateField(verbose_name='Enter  Experience End Date')),
                ('exp_description', models.TextField(verbose_name='Enter  Experience Description')),
                ('edu_school', models.CharField(max_length=20, verbose_name='Enter  Education School')),
                ('edu_degree', models.CharField(max_length=20, verbose_name='Enter  Education Degree')),
                ('edu_city', models.CharField(max_length=20, verbose_name='Enter  Education City')),
                ('edu_start_date', models.DateField(verbose_name='Enter  Education Start Date')),
                ('edu_end_date', models.DateField(verbose_name='Enter  Education End Date')),
                ('edu_description', models.TextField(verbose_name='Enter  Education Description')),
                ('proj_name', models.CharField(max_length=20, verbose_name='Enter  Project Name')),
                ('proj_link', models.TextField(verbose_name='Enter  Project Link')),
                ('proj_description', models.TextField(verbose_name='Enter  Project Description')),
                ('skills', models.TextField(verbose_name='Enter Name')),
            ],
        ),
    ]
