# Generated by Django 5.1.2 on 2025-01-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_remove_user_data_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='edu_end_date',
            field=models.JSONField(verbose_name='Enter  Education End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='edu_start_date',
            field=models.JSONField(verbose_name='Enter  Education Start Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_end_date',
            field=models.JSONField(verbose_name='Enter  Experience End Date'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='exp_start_date',
            field=models.JSONField(verbose_name='Enter  Experience Start Date'),
        ),
    ]
