# Generated by Django 5.1.2 on 2025-01-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0003_alter_user_data_edu_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='skills',
            field=models.TextField(verbose_name='Enter skills'),
        ),
    ]
